In [1]:
import numpy as np
np.random.seed(0) # seed for repoductibility

x1 = np.random.randint(10, size=6) #One Dimensional Array
x2 = np.random.randint(10, size=(3,4)) #Two-Dimensional Array
x3 = np.random.randint(10, size=(3, 4, 5)) #Three Dimensional Array

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [7]:
print("dtype:", x3.dtype)

dtype: int64


In [9]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [11]:
x1

array([5, 0, 3, 3, 7, 9])

In [13]:
x1[0]

5

In [15]:
x1[4]

7

In [17]:
x1[-1]

9

In [19]:
x1[-2]

7

In [21]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
x2[0,0]

3

In [25]:
x2[2,0]

1

In [27]:
x2[2,-1]

7

In [29]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [31]:
x1[0] = 3.14159 #this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

In [35]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [39]:
x[5:] #elements after index 5

array([5, 6, 7, 8, 9])

In [41]:
x[4:7] #middle subarray

array([4, 5, 6])